# Site settings
title: Alex Polak
email: alexpolak@gmail.com
description: > 
  Software Developer | Machine Learning | Networking
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexandrapolak.github.io" # the base hostname & protocol for your site
github_username:  alexandrapolak

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Software Developer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
